image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-release:
  stage: build
  script:
    - |
      docker build \
        --build-arg APP_NAME=gate \
        --build-arg APP_VSN=0.1.0 \
        --build-arg REL_ENV=prod \
        -t $CI_REGISTRY_IMAGE:latest \
        .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-dev:
  stage: build
  script:
    - |
      docker build \
        --build-arg APP_NAME=gate \
        --build-arg APP_VSN=0.1.0 \
        --build-arg REL_ENV=prod \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG \
        .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
