image: docker:latest

services:
  - docker:dind

stages:
  - prepare
  - build
  - test
  - deploy

before_script:
  - |
    echo "$CI_REGISTRY_PASSWORD" | \
      docker login \
        --username "$CI_REGISTRY_USER" \
        --password-stdin \
        $CI_REGISTRY

prepare-base:
  stage: prepare
  script:
    - |
      docker build \
        --pull \
        --file build/build.Dockerfile \
        --tag $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-build \
        .
    - docker push $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-build
    - |
      docker build \
        --pull \
        --file build/base.Dockerfile \
        --tag $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-base \
        .
    - docker push $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-base
    - |
      docker build \
        --pull \
        --build-arg BUILD_IMAGE=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-build \
        --file build/deps.Dockerfile \
        --tag $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-deps \
        .
    - docker push $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-deps

build-release:
  stage: build
  script:
    - |
      docker build \
        --build-arg DEPS_IMAGE=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-deps \
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-base \
        --build-arg APP_NAME=elven_gard_bastion \
        --build-arg APP_VSN=2.0.0-beta.1 \
        -t $CI_REGISTRY_IMAGE:latest \
        .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-dev:
  stage: build
  script:
    - |
      docker build \
        --build-arg DEPS_IMAGE=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-deps \
        --build-arg BASE_IMAGE=$CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG-base \
        --build-arg APP_NAME=elven_gard_bastion \
        --build-arg APP_VSN=2.0.0-beta.1 \
        -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG \
        .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
