apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elven-gard.fullname" . }}-cluster
  labels:
    app.kubernetes.io/name: {{ include "elven-gard.name" . }}
    helm.sh/chart: {{ include "elven-gard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  gossip-secret: {{ .Values.gossipSecret }}
  erlang-cookie: {{ .Values.erlangCookie }}
