apiVersion: v1
kind: Service
metadata:
  name: {{ include "elven-gard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "elven-gard.name" . }}
    helm.sh/chart: {{ include "elven-gard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "elven-gard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
