apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elven-gard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "elven-gard.name" . }}
    helm.sh/chart: {{ include "elven-gard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: "elven-gard"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elven-gard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elven-gard.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: elven
        image: elven_gard_bastion/nostale
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ default 4123 .Values.gatePort }}
          name: gate
        - containerPort: {{ default 4124 .Values.worldPort }}
          name: world
        - containerPort: 4369
          name: erlang-daemon
        - containerPort: 45892
          name: erlang-discover
        - containerPort: 49200
          name: erlang-mesh
        env:
          - name: ELVEN_GARD_CITADEL
            value: {{ default 4124 .Values.worldPort }}
          - name: GOSSIP_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "elven-gard.fullname" . }}-cluster
                key: gossip-secret
          - name: ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: {{ include "elven-gard.fullname" . }}-cluster
                key: erlang-cookie
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DEPLOYMENT_NAME
            value: {{ .Release.Name }}
